import re
from difflib import SequenceMatcher

MOJIBAKE_SEQ_RE = re.compile(
    r"(?:[\u0420\u0421][\u0400-\u045F\u00A0-\u00BF]){2,}"
    r"|(?:[\u00D0\u00D1][\u0080-\u00BF]){2,}"
)
CYRILLIC_CORE_RE = re.compile(r"[\u0410-\u044F\u0401\u0451]")
MOJIBAKE_NOISE_RE = re.compile(r"[\u0402-\u040F\u0452-\u045F]")

URL_RE = re.compile(r'https?://[^\s<>"]+')
SOURCE_LINE_RE = re.compile(
    r"^\s*(source|источник|official materials)\s*:",
    re.IGNORECASE,
)

GENERIC_SOLUTION_MARKERS = (
    "внимательно выписываем данные задачи",
    "выбираем подходящий метод",
    "см. итоговый вывод",
    "extract all numeric and logical constraints",
    "apply an appropriate method step by step",
    "validate the result against every condition",
    "given (short):",
    "final answer: see detailed reasoning",
)
PLACEHOLDER_SOLUTION_MARKERS = (
    "official materials",
    "see editorial",
    "см. решение",
    "см. разбор",
    "решение (сгенерировано нейросетью): идея:",
    "(сгенерировано нейросетью)",
    "solution (generated by ai): idea:",
)
UNAVAILABLE_SOLUTION_MARKERS = (
    "vsosh_enrich_fallback",
    "groq ai не смог сгенерировать ответ",
    "qwen ai не смог сгенерировать ответ",
    "локальная модель не смогла сгенерировать ответ",
    "решение временно недоступно",
    "официальное решение всош пока не найдено автоматически",
    "проверьте pdf-источники задачи",
    "не удалось прочитать pdf условия",
    "solution is temporarily unavailable",
)


def _cyrillic_score(text: str) -> int:
    return len(CYRILLIC_CORE_RE.findall(str(text or "")))


def _fix_mojibake_text(value: str) -> str:
    raw = str(value or "")
    if not raw:
        return raw

    candidates = [raw]
    for source_encoding in ("cp1251", "latin1", "cp1252"):
        try:
            fixed = raw.encode(source_encoding, errors="strict").decode("utf-8", errors="strict")
            candidates.append(fixed)
            for second_encoding in ("cp1251", "latin1"):
                try:
                    fixed_twice = fixed.encode(second_encoding, errors="strict").decode("utf-8", errors="strict")
                    candidates.append(fixed_twice)
                except Exception:
                    continue
        except Exception:
            continue

    def _score(text: str) -> int:
        mojibake_penalty = 30 if MOJIBAKE_SEQ_RE.search(text) else 0
        mojibake_noise_penalty = len(MOJIBAKE_NOISE_RE.findall(text)) * 3
        question_penalty = text.count("?") * 2
        replacement_penalty = text.count("�") * 4
        return _cyrillic_score(text) * 3 - mojibake_penalty - mojibake_noise_penalty - question_penalty - replacement_penalty

    best = max(candidates, key=_score)
    return best if _score(best) >= _score(raw) + 4 else raw


def normalize_text_value(value) -> str:
    return _fix_mojibake_text(str(value or "")).strip()


def strip_source_lines(text: str) -> str:
    if not text:
        return ""
    fixed = _fix_mojibake_text(str(text))
    lines = [line for line in fixed.splitlines() if not SOURCE_LINE_RE.match(line.strip())]
    return "\n".join(lines).strip()


def clean_solution_explanation_text(text: str) -> str:
    if not text:
        return ""
    fixed = _fix_mojibake_text(str(text))
    lines = [line for line in fixed.splitlines() if not SOURCE_LINE_RE.match(line.strip())]
    cleaned = "\n".join(lines).strip()
    cleaned = URL_RE.sub("", cleaned)
    return cleaned.strip(" \n:-")


def is_unavailable_solution_text(text: str) -> bool:
    normalized = clean_solution_explanation_text(_fix_mojibake_text(text or "")).lower()
    if not normalized:
        return False
    return any(marker in normalized for marker in UNAVAILABLE_SOLUTION_MARKERS)


def is_generic_solution_explanation(text: str) -> bool:
    normalized = clean_solution_explanation_text(_fix_mojibake_text(text or "")).lower()
    if not normalized:
        return True
    if is_unavailable_solution_text(normalized):
        return True
    if any(marker in normalized for marker in PLACEHOLDER_SOLUTION_MARKERS):
        return True
    hits = sum(1 for marker in GENERIC_SOLUTION_MARKERS if marker in normalized)
    return hits >= 2


def first_sentence(text: str) -> str:
    clean = strip_source_lines(text or "")
    if not clean:
        return ""
    parts = re.split(r"(?<=[.!?])\s+", clean, maxsplit=1)
    return parts[0].strip()


def simplify_text_for_search(text: str) -> str:
    raw = normalize_text_value(text or "").lower()
    return re.sub(r"[^a-zа-яё0-9]+", "", raw, flags=re.IGNORECASE)


def normalize_text_for_dedupe(text: str) -> str:
    return re.sub(r"\s+", " ", normalize_text_value(text or "")).strip().lower()


def looks_like_duplicate_paragraph(current_norm: str, previous_norm: str) -> bool:
    if not current_norm or not previous_norm:
        return False
    if current_norm == previous_norm:
        return True
    min_len = min(len(current_norm), len(previous_norm))
    max_len = max(len(current_norm), len(previous_norm))
    if min_len < 70:
        return False
    if current_norm in previous_norm or previous_norm in current_norm:
        return True
    if abs(len(current_norm) - len(previous_norm)) > max(240, int(max_len * 0.5)):
        return False
    ratio = SequenceMatcher(a=current_norm, b=previous_norm, autojunk=False).ratio()
    threshold = 0.90 if max_len >= 220 else 0.96
    return ratio >= threshold


def merge_solution_chunks(base_text: str, next_chunk: str) -> str:
    base = normalize_text_value(base_text or "")
    chunk = normalize_text_value(next_chunk or "")
    if not base:
        return chunk
    if not chunk:
        return base
    if chunk in base:
        return base

    max_overlap = min(len(base), len(chunk), 2000)
    for overlap in range(max_overlap, 120, -1):
        if base[-overlap:] == chunk[:overlap]:
            return f"{base}{chunk[overlap:]}".strip()

    probe = chunk[:220]
    if len(probe) >= 120:
        probe_index = base.rfind(probe)
        if probe_index >= 0:
            overlap = len(base) - probe_index
            if 120 <= overlap <= len(chunk):
                return f"{base}{chunk[overlap:]}".strip()

    return f"{base}\n\n{chunk}".strip()


def clean_generated_solution_text(solution_text: str) -> str:
    text = normalize_text_value(solution_text or "")
    if not text:
        return ""
    # Strip [CONTINUE] marker — it's a generation control token, not part of the solution
    text = re.sub(r"\s*\[CONTINUE\]\s*$", "", text, flags=re.IGNORECASE).strip()
    # Rejoin "Итоговый\nответ:" split across lines
    text = re.sub(r"(итоговый)\s*[\r\n]+\s*(ответ\s*:)", r"Ответ:", text, flags=re.IGNORECASE)
    text = re.sub(r"(?i)итоговый\s+ответ\s*:", "Ответ:", text)
    
    # If the model hallucinates multiple "Ответ:" blocks, replace all but the last one
    matches = list(re.finditer(r"(?i)(^|\n)[\s\-*]*ответ\s*:", text))
    if len(matches) > 1:
        last_match_idx = matches[-1].start()
        before_last = text[:last_match_idx]
        before_last = re.sub(r"(?i)ответ\s*:", "Промежуточный вывод:", before_last)
        text = before_last + text[last_match_idx:]

    if not text:
        return ""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    if not text:
        return ""

    paragraphs = [p.strip() for p in re.split(r"\n{2,}", text) if p.strip()]
    unique_paragraphs = []
    seen_paragraphs = []
    for paragraph in paragraphs:
        normalized = normalize_text_for_dedupe(paragraph)
        if normalized and len(normalized) >= 50:
            if any(looks_like_duplicate_paragraph(normalized, prev) for prev in seen_paragraphs):
                continue
        if normalized:
            seen_paragraphs.append(normalized)
        unique_paragraphs.append(paragraph)
    text = "\n\n".join(unique_paragraphs)

    deduped_lines = []
    prev_norm = ""
    seen_section_headers = set()
    section_header_re = re.compile(r"^(?:\*\*)?\s*\d+[.)]\s+.+?(?:\*\*)?:?\s*$", re.IGNORECASE)
    for line in text.splitlines():
        normalized_line = normalize_text_for_dedupe(line)
        stripped_line = line.strip()
        if section_header_re.match(stripped_line):
            if normalized_line and normalized_line in seen_section_headers:
                continue
            if normalized_line:
                seen_section_headers.add(normalized_line)
        if normalized_line and normalized_line == prev_norm and len(normalized_line) >= 18:
            continue
        deduped_lines.append(line.rstrip())
        if normalized_line:
            prev_norm = normalized_line
    text = "\n".join(deduped_lines)
    return re.sub(r"\n{3,}", "\n\n", text).strip()
